version: "3"

services:
  gateway:
    build:
      context: .docker/php/8.1-apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./gateway:/var/www/html

  users:
    build:
      context: .docker/php/8.1-apache
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    entrypoint: php bin/console user:create-http
    volumes:
      - ./users:/var/www/html

  orders:
    build:
      context: .docker/php/8.1-apache
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    entrypoint: php bin/console order:create-http
    volumes:
      - ./orders:/var/www/html

  composer:
    image: composer/composer
    command:
      - composer install
    volumes:
      - ./:/app


  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"


