version: "3"

services:
  gateway:
    build:
      context: .docker/php/8.1-apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./gateway:/var/www/html

  users:
    build:
      context: .docker/orders
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./users:/var/www/html

  orders:
    build:
      context: .docker/orders
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./orders:/var/www/html

  composer:
    image: composer/composer
    command:
      - composer install
    volumes:
      - ./:/app


  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    env_file:
      - .env

